package:
  name: fisea
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ../../

build:
  number: 0
  script:
    - unset CMAKE_GENERATOR && {{ PYTHON }} -m pip install . -vv  # [not win]
    - {{ PYTHON }} -m pip install . -vv  # [win]

requirements:
  build:
    - python
    - {{ compiler('cxx') }}

  host:
    - cmake
    - ninja
    - python
    - pip
    - scikit-build-core
    - pybind11 >=2.10.0

  run:
    - python


test:
  imports:
    - fisea
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  summary: An Project to implement pytorch.
  license_file: LICENSE