jobs:
  CI:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: Jimver/cuda-toolkit@master
      id: cuda-toolkit
      with:
        log-file-suffix: '${{matrix.os}}.txt'
    - run: echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
    
    - run: echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
    
    - run: nvcc -V
