name: NVCC

on: [push, workflow_dispatch]
  
jobs:

  build:
  
    runs-on: windows-2019

    steps:

      - uses: actions/checkout@v3
          
      - name: clexe 
        shell: |
          powershell 
          
        run: |
          cd Actions/NVCC/
          
          .\simplest.ps1
